
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update && sudo apt-get install -y python-pip linkchecker  libgdal-dev libproj-dev libjpeg-dev libpng-dev libgeos-dev libudunits2-dev
  - mkdir -p ~/.linkchecker
  - echo -e '[checking]\nsslverify=0' > ~/.linkchecker/linkcheckerrc

# DO NOT CHANGE THE CODE ABOVE


language: r
r:
  - oldrel
  - release
  - devel
